### ISSUE TITLE
名稱錯誤

### ISSUE THREAD

**Issue by StanHsieh** [nukr/street_name#1]
新北市 
蘆洲市→蘆洲區
八里鄉→八里區

桃園縣→桃園市
<整區都要改...>
→中壢區
→平鎮區
→龍潭區
→楊梅區
→新屋區
→觀音區
→桃園區
→龜山區
→八德區
→大溪區
→復興區
→大園區
→蘆竹區

苗栗
南莊鄉→南庄鄉

嘉義縣
樸子市→朴子市

花蓮
缺少→富里鄉

**Comment by nukr** [comment]
done
